FROM pelias/geonames:latest
WORKDIR /code/pelias/geonames
COPY lib/streams/peliasDocGenerator.js ./lib/streams/peliasDocGenerator.js
COPY lib/streams/featureCodeFilterStream.js ./lib/streams/featureCodeFilterStream.js